// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'emoji_container': string;
  'home_popover_container': string;
  'input_action': string;
  'menu_container': string;
  'message_popover_container': string;
}
export const cssExports: CssExports;
export default cssExports;
