// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'content': string;
  'content_formWrapper': string;
  'content_subtitle': string;
  'content_title': string;
  'wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
