// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'EditProfile': string;
  'EditProfileForm': string;
  'EditProfile_addAvatarIcon': string;
  'EditProfile_avatar': string;
  'EditProfile_heading': string;
  'EditProfile_saveBtn': string;
  'EditProfile_saveBtnVisible': string;
  'search_wrapper': string;
  'sidebar': string;
  'sidebar_anim': string;
  'sidebar_close': string;
  'sidebar_header': string;
  'sidebar_track': string;
}
export const cssExports: CssExports;
export default cssExports;
