// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'search_wrapper': string;
  'sidebar': string;
  'sidebar_anim': string;
  'sidebar_close': string;
  'sidebar_header': string;
  'sidebar_track': string;
}
export const cssExports: CssExports;
export default cssExports;
