// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'adornment_icon': string;
  'micro_icon': string;
  'send_icon': string;
  'submit_button': string;
}
export const cssExports: CssExports;
export default cssExports;
