// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'paused': string;
  'record-blink': string;
  'runner': string;
}
export const cssExports: CssExports;
export default cssExports;
