// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'buttonLoader': string;
  'disabled': string;
  'loading': string;
  'modalButton': string;
}
export const cssExports: CssExports;
export default cssExports;
