// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actionsButtonWrapper': string;
  'avatar': string;
  'mainHeaderActionsButton': string;
  'middle_header': string;
  'middle_header_actions': string;
}
export const cssExports: CssExports;
export default cssExports;
