// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'selectMode': string;
  'textarea': string;
}
export const cssExports: CssExports;
export default cssExports;
