// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'avatar': string;
  'badge': string;
  'dialog': string;
  'unread': string;
}
export const cssExports: CssExports;
export default cssExports;
