// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'loader': string;
  'loaderAnimationWrapper': string;
  'loaderSvg': string;
  'wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
