export enum ErrorCode {
    BAD_REQUEST = "BAD_REQUEST",
    UNAUTORIEZED = "UNAUTORIEZED",
    FORBIDDEN = "FORBIDDEN",
    NOT_FOUND = "NOT_FOUND",
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
    UNKNOWN_ERROR = "UNKNOWN_ERROR",
};