// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actionsButtonWrapper': string;
  'avatar': string;
  'home_grid': string;
  'home_main': string;
  'home_wrapper': string;
  'mainHeaderActionsButton': string;
  'message_input': string;
  'messages_wrapper': string;
  'middle_column': string;
  'middle_header': string;
  'middle_header_actions': string;
  'search_wrapper': string;
  'searchbar': string;
  'searchbar_anim': string;
  'searchbar_open': string;
  'sidebar': string;
  'sidebar_anim': string;
  'sidebar_close': string;
  'sidebar_header': string;
  'sidebar_track': string;
}
export const cssExports: CssExports;
export default cssExports;
