// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'adornment': string;
  'adornmentIcon': string;
  'circularProgress': string;
  'endAdornment': string;
  'searchInput': string;
  'searchInputWrapper': string;
  'startAdornment': string;
}
export const cssExports: CssExports;
export default cssExports;
