// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'group': string;
  'group_header': string;
  'group_header_suffix': string;
  'group_header_title': string;
}
export const cssExports: CssExports;
export default cssExports;
