// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'contentGrid': string;
  'contentInput': string;
  'contentInputWrap': string;
  'contentItem': string;
  'contentItemIcon': string;
  'contentItemInfo': string;
  'contentItemMedia': string;
  'contentItemSubtitle': string;
  'contentItemTitle': string;
  'submitButton': string;
}
export const cssExports: CssExports;
export default cssExports;
